services:
  db:
    image: postgres:16-alpine
    container_name: project-ab-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: arnav
      POSTGRES_PASSWORD: arnav
      POSTGRES_DB: project_ab
    ports:
      - "5432:5432"
    volumes:
      - project-ab-db:/var/lib/postgresql/data

volumes:
  project-ab-db:
